# Generated by Django 5.1.4 on 2025-01-03 18:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('package', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('registration_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_details', models.DecimalField(decimal_places=2, max_digits=10)),
                ('whats_included', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('whats_not_included', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('itinerary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_img', models.ImageField(upload_to='event/covers')),
            ],
        ),
    ]
