# Generated by Django 5.1.4 on 2025-01-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='country',
        ),
    ]
