# Generated by Django 5.1.4 on 2025-01-09 01:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_userdetails_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('course_desc', ckeditor.fields.RichTextField()),
                ('itinerary', ckeditor.fields.RichTextField()),
                ('whats_included', ckeditor.fields.RichTextField()),
                ('whats_not_included', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('no_of_jumps', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('level_desc', models.CharField(max_length=50)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.coursedetails')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='trainer',
            field=models.ManyToManyField(to='events.trainers'),
        ),
    ]
