# Generated by Django 5.1.4 on 2025-01-10 13:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_coursedetails_trainers_userdetails_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='level_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
