# Generated by Django 5.1.4 on 2025-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_courselevel_level_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='trainers'),
        ),
    ]
