# Generated by Django 5.1.4 on 2025-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_trainers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='trainer',
            field=models.ManyToManyField(blank=True, null=True, to='events.trainers'),
        ),
    ]
