# Generated by Django 5.1.4 on 2025-01-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_coursedetails_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.coursedetails')),
            ],
        ),
    ]
