# Generated by Django 5.1.4 on 2025-01-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
    ]
