# Generated by Django 5.1.4 on 2025-01-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_course_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='registration_fees',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='total_fees',
            field=models.BigIntegerField(default=''),
        ),
    ]
