# Generated by Django 5.1.4 on 2025-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_coursedetails_registration_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='registration_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='total_fees',
            field=models.BigIntegerField(default=0),
        ),
    ]
