# Generated by Django 5.1.4 on 2025-01-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_coursedetails_registration_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='registration_fees',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='total_fees',
        ),
    ]
