# Generated by Django 5.1.4 on 2025-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_coursedetails_registration_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='registration_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='total_fees',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
