# Generated by Django 5.1.4 on 2025-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_coursedetails_registration_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='total_fees',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
