# Generated by Django 5.1.4 on 2025-01-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_coursedetails_total_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
