# Generated by Django 5.1.4 on 2025-01-20 05:22

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0017_coursedetails_total_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('height', models.FloatField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('experience', models.CharField(choices=[('BEG', 'BEGINNER (with less then 3 jumps)'), ('INT', 'INTERMIDIATE (with more the 5 jumps less then 10)'), ('ADV', 'ADVANCE (with AFF or WSJC certifications)')], max_length=50)),
                ('special_req', models.CharField(blank=True, max_length=254, null=True)),
                ('emergency_contact_person_name', models.CharField(max_length=100)),
                ('emergency_contact_person_relation', models.CharField(max_length=50)),
                ('emergency_contact_person_number', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
