# Generated by Django 5.1.4 on 2025-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_course_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
