# Generated by Django 5.1.4 on 2025-01-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_event_booking_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_booking',
            name='course',
        ),
    ]
